apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver-service;Database=QLThuVien;User Id=sa;Password=Phong@0909;TrustServerCertificate=True;"