apiVersion: apps/v1
kind: Deployment
metadata:
  name: qlthuvien-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qlthuvien
  template:
    metadata:
      labels:
        app: qlthuvien
    spec:
      containers:
        - name: qlthuvien
          image: fong62/qlthuvien:${IMAGE_TAG}
          ports:
            - containerPort: 80