apiVersion: v1
kind: Service
metadata:
  name: qlthuvien-service
spec:
  selector:
    app: qlthuvien
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort