apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
        - name: ACCEPT_EULA  # Chấp nhận điều khoản
          value: "Y"
        - name: SA_PASSWORD  # Sử dụng Secret
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SA_PASSWORD
        ports:
        - containerPort: 1433  # Cổng mặc định của SQL Server
        volumeMounts:
        - mountPath: /var/opt/mssql  # Thư mục lưu trữ dữ liệu
          name: sql-data
      volumes:
      - name: sql-data
        persistentVolumeClaim:
          claimName: sql-pvc  # Liên kết với PVC đã tạo